apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-application
spec:
  params:
    - name: app_name
      type: string
    - name: dev_project
      type: string
  resources:
    inputs:
      - name: image
        type: image
  steps:
    - args:
        - >-
          echo '### Cleaning existing resources in DEV env ###'

          oc project $(inputs.params.dev_project)

          oc delete all -l app=$(inputs.params.app_name)

          sleep 5


          echo '### Creating a new app in DEV env ###'

          oc new-app --name $(inputs.params.app_name) -i
          $(inputs.params.app_name)

          oc expose svc/$(inputs.params.app_name)
      command:
        - /bin/bash
        - '-c'
      image: 'quay.io/openshift/origin-cli:latest'
      name: deploy
      resources: {}
