apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wait-for-stage-deployment
spec:
  params:
    - name: app_name
      type: string
    - name: stage_project
      type: string
  steps:
    - args:
        - >-
          echo Verify pod deployment for $(inputs.params.app_name);

          while true; do pods=$(oc get pods -l
          deployment=$(inputs.params.app_name) -n $(inputs.params.stage_project)
          ); if [ -z "$pods" ];then echo "Waiting for pods to be created...";
          sleep 20; continue;fi; pod_status=$(oc get pods -l
          deployment=$(inputs.params.app_name) -n $(inputs.params.stage_project)
          | awk 'FNR>1 {print $3}'); echo "Pod status: $pod_status";  if ! grep
          -qv 'Running'<<<"$$pod_status";then echo 'Deployment pods are
          ready';break;else sleep 10;fi; done;    route=$(oc get route
          $(inputs.params.app_name) | awk 'FNR==2 {print $2}'); echo "Deployment
          to Staging env is complete. Access at http://$route";
      command:
        - /bin/bash
        - '-c'
      image: 'quay.io/openshift/origin-cli:latest'
      name: wait-for-deployment
      resources: {}
