apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  params:
    - default: ''
      description: name of application
      name: app_name
      type: string
    - default: ''
      description: Development project name
      name: dev_project
      type: string
    - default: ''
      description: Staging project name
      name: stage_project
      type: string
  resources:
    - name: git-repo
      type: git
    - name: image
      type: image
  tasks:
    - name: deploy-application
      params:
        - name: app_name
          value: books
        - name: dev_project
          value: demo-pipeline
      resources:
        inputs:
          - name: image
            resource: image
      runAfter:
        - run-unit-test
      taskRef:
        kind: Task
        name: deploy-application
    - name: wait-for-deployment
      params:
        - name: app_name
          value: books
        - name: dev_project
          value: demo-pipeline
      runAfter:
        - deploy-application
      taskRef:
        kind: Task
        name: wait-for-deployment
    - name: promote-to-stage
      params:
        - name: dev_project
          value: demo-pipeline
        - name: stage_project
          value: loken-stage
        - name: app_name
          value: books
      runAfter:
        - wait-for-deployment
      taskRef:
        kind: Task
        name: promote-to-stage
    - name: deploy-to-stage
      params:
        - name: app_name
          value: books
        - name: stage_project
          value: loken-stage
      runAfter:
        - promote-to-stage
      taskRef:
        kind: Task
        name: deploy-to-stage
    - name: wait-for-stage-deployment
      params:
        - name: app_name
          value: books
        - name: stage_project
          value: loken-stage
      runAfter:
        - deploy-to-stage
      taskRef:
        kind: Task
        name: wait-for-stage-deployment
    - name: s2i-build-image
      params:
        - name: VERSION
          value: '10'
        - name: PATH_CONTEXT
          value: books
        - name: TLSVERIFY
          value: 'false'
      resources:
        inputs:
          - name: source
            resource: git-repo
        outputs:
          - name: image
            resource: image
      taskRef:
        kind: ClusterTask
        name: s2i-nodejs
    - name: run-unit-test
      resources:
        inputs:
          - name: git-repo
            resource: git-repo
          - name: image
            resource: image
      runAfter:
        - s2i-build-image
      taskRef:
        kind: Task
        name: run-unit-test
