apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: ui-image
spec:
  params:
    - name: url
      value: >-
        image-registry.openshift-image-registry.svc:5000/demo-pipeline/books:latest
  type: image
